---
# tasks file for Instala-tools


    - name: "Instalando apache " 
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ LISTADO_DE_PROGRAMAS }}"

