---
# tasks file for TP_INI

- name: "Rol: TP_INI - Grupo: {{ municipalidad-de-la-utn }}"
  debug:
    msg: "Inicio de tareas dentro del Rol: TP_INI"

- name: "Alta de groups Secundarios del usuario "
  become: yes
  group:
    name: "municipalidad-de-la-utn"
    state: present
  tags:
    - Alta-Usuarios

- name: "Agregando group Primario del usuario "
  become: yes
  group:
    name: "{{ item.USERNAME }}"
    state: present
  with_items: "{{ LIST_USUARIOS }}"
  tags:
    - Alta-Usuarios

                                                                         
- name: "Alta y/o Actualizacion del usuario"
  become: yes
  user:
    name: "{{ item.USERNAME }}"
    password: "{{ item.HASH }}"
    group: "{{ LIST_GROUPS }}"
    groups: "municipalidad-de-la-utn"
    state: present
    append: yes
  with_items: "{{ LIST_USUARIOS }}"
  tags:
    - Alta-Usuarios

