---
- hosts: 
#  - all
  - testing
  - produc

  # Variables Globales
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI

    - include_role:
        name: Alta_Usuarios_municipalidad-de-la-utn
   
    - include_role:
        name: Instala-tools 

    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

