---
- hosts: 
#  - all
  - testing
  - produccion

  # Variables Globales
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI
  tasks:
    - include_role:
        name: Alta_Usuarios_municipalidad-de-la-utn
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

